# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=200)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elections.Voter'),
        ),
    ]
