# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN')], max_length=3)),
                ('category', models.CharField(choices=[('tops', 'Tops'), ('bottoms', ' Bottoms'), ('outerwear', ' Outerwear'), ('footwear', 'Footwear'), ('accessories', ' Accessories')], max_length=6)),
            ],
        ),
    ]
