# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_remove_productdetails_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='category',
            field=models.CharField(choices=[('tops', 'Tops'), ('bottoms', ' Bottoms'), ('outerwear', ' Outerwear'), ('footwear', 'Footwear'), ('accessories', ' Accessories')], max_length=10),
        ),
    ]
