# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20170908_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='gender',
            field=models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN')], max_length=20),
        ),
    ]
