# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 05:19
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_auto_20170908_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='productcost',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='productdescription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='productsize',
            field=models.CharField(choices=[('s', 'S'), ('xs', 'XS'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='productname',
            field=models.CharField(max_length=40),
        ),
    ]
