# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 05:23
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_auto_20170908_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='color',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='productcolor',
            field=colorful.fields.RGBColorField(default='#FF0000'),
        ),
    ]
