# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 06:26
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessoriesname', models.CharField(max_length=20)),
                ('accessoriesimage', models.ImageField(upload_to=b'')),
                ('gender', models.CharField(choices=[(b'men', b'MEN'), (b'women', b'WOMEN')], max_length=20)),
                ('accessoriescost', models.CharField(default=b'', max_length=20)),
                ('accessoriescategory', models.CharField(choices=[(b'mobiles', b'MOBILES'), (b'jewel', b'JEWEL'), (b'handbags', b'HANDBAGS'), (b'watches', b'WATCHES'), (b'handycraft', b'HANDYCRAFTS'), (b'trimmers', b'TRIMMERS')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bottoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottomname', models.CharField(max_length=20)),
                ('bottomimage', models.ImageField(upload_to=b'')),
                ('gender', models.CharField(choices=[(b'men', b'MEN'), (b'women', b'WOMEN')], max_length=20)),
                ('bottomcost', models.CharField(default=b'', max_length=20)),
                ('bottomdescription', models.CharField(default=b'', max_length=100)),
                ('bottomsize', models.CharField(choices=[(b's', b'S'), (b'xs', b'XS'), (b'm', b'M'), (b'l', b'L'), (b'xl', b'XL'), (b'xxl', b'XXL')], default=b'', max_length=5)),
                ('bottomcolor', colorful.fields.RGBColorField(default=b'#FF0000')),
            ],
        ),
        migrations.CreateModel(
            name='Footwears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footwearname', models.CharField(max_length=20)),
                ('footwearimage', models.ImageField(upload_to=b'')),
                ('gender', models.CharField(choices=[(b'men', b'MEN'), (b'women', b'WOMEN')], max_length=20)),
                ('footwearcost', models.CharField(default=b'', max_length=20)),
                ('footweardescription', models.CharField(default=b'', max_length=100)),
                ('footwearsize', models.CharField(choices=[(b's', b'S'), (b'xs', b'XS'), (b'm', b'M'), (b'l', b'L'), (b'xl', b'XL'), (b'xxl', b'XXL')], default=b'', max_length=5)),
                ('footwearcolor', colorful.fields.RGBColorField(default=b'#FF0000')),
            ],
        ),
        migrations.CreateModel(
            name='Outerwears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outerwearname', models.CharField(max_length=20)),
                ('outerwearimage', models.ImageField(upload_to=b'')),
                ('gender', models.CharField(choices=[(b'men', b'MEN'), (b'women', b'WOMEN')], max_length=20)),
                ('outerwearcost', models.CharField(default=b'', max_length=20)),
                ('outerweardescription', models.CharField(default=b'', max_length=100)),
                ('outerwearsize', models.CharField(choices=[(b's', b'S'), (b'xs', b'XS'), (b'm', b'M'), (b'l', b'L'), (b'xl', b'XL'), (b'xxl', b'XXL')], default=b'', max_length=5)),
                ('outerwearcolor', colorful.fields.RGBColorField(default=b'#FF0000')),
            ],
        ),
        migrations.CreateModel(
            name='Tops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topname', models.CharField(max_length=20)),
                ('topimage', models.ImageField(upload_to=b'')),
                ('gender', models.CharField(choices=[(b'men', b'MEN'), (b'women', b'WOMEN')], max_length=20)),
                ('topcost', models.CharField(default=b'', max_length=20)),
                ('topdescription', models.CharField(default=b'', max_length=100)),
                ('topsize', models.CharField(choices=[(b's', b'S'), (b'xs', b'XS'), (b'm', b'M'), (b'l', b'L'), (b'xl', b'XL'), (b'xxl', b'XXL')], default=b'', max_length=5)),
                ('topcolor', colorful.fields.RGBColorField(default=b'#FF0000')),
            ],
        ),
    ]
