# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 07:26
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='accessoriescolor',
            field=colorful.fields.RGBColorField(default=b'#FF0000'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='accessoriesdescription',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='accessories',
            name='accessoriessize',
            field=models.CharField(choices=[(b's', b'S'), (b'xs', b'XS'), (b'm', b'M'), (b'l', b'L'), (b'xl', b'XL'), (b'xxl', b'XXL')], default=b'', max_length=5),
        ),
    ]
